Chore/deprecate
teknologi-umum/bot pull request #142
Opened 2021-11-23 05:16 UTC by aldy505

2021-11-23 05:23 UTC, ronnygunawan requested changes

2021-11-23 05:23 UTC, ronnygunawan commented on src/services/bliding-ej/index.js
>  export function register(bot) {
ngga didelete sekalian?

2021-11-23 05:23 UTC, ronnygunawan commented on src/services/covid/index.js
>    bot.command("covid", (context) => covid(context, cache));
ngga didelete sekalian?

2021-11-23 05:23 UTC, ronnygunawan commented on src/services/meme/index.js
> +      if (error?.msBeforeNext)
inilah kenapa lebih enak pake  `"curly": ["error", "multi-line"]`

2021-11-23 05:23 UTC, ronnygunawan commented on src/services/pastebin/index.js
> -  return [
kenapa deprecated?

2021-11-23 05:23 UTC, ronnygunawan commented on src/utils/kv.js
> +    return this.store[key] || "";
use `??`

2021-11-23 05:24 UTC, ronnygunawan commented on src/utils/kv.js
> +    this.store[key] = value;
kalau mau konsisten bisa dibikin:

```js
if (value == null || value === "") {
  delete this.store[key];
} else {
  this.store[key] = value;
}
```

2021-11-23 05:30 UTC, aldy505 commented on src/services/meme/index.js
> +      if (error?.msBeforeNext)
yes I know

2021-11-23 05:30 UTC, aldy505 commented on src/services/pastebin/index.js
> -  return [
ga ada yang pake

2021-11-23 05:30 UTC, aldy505 commented on src/utils/kv.js
> +    return this.store[key] || "";
di branch sebelah om. disini ga dipake.

2021-11-23 05:30 UTC, aldy505 commented on src/services/bliding-ej/index.js
>  export function register(bot) {
pengen sih hmm, cuma namanya deprecate

2021-11-23 05:30 UTC, aldy505 commented on src/services/covid/index.js
>    bot.command("covid", (context) => covid(context, cache));
nanti kalo udah boleh keluar gapake masker

2021-11-23 05:31 UTC, aldy505 commented on src/utils/kv.js
> +    this.store[key] = value;
delete is a dangerous keyword hmm

2021-11-26 07:37 UTC, ronnygunawan approved these changes

2021-11-26 09:50 UTC, elianiva commented on src/services/search/filter.js
> +        o.snippet.toLowerCase().includes(match)) {return false;}
dibikin gini aja ngga bisa?

```js
const result = search.filter((o) => {
  for (const match of dedupeMatches) {
    if (
      o.href.toLowerCase().includes(match) ||
      o.title.toLowerCase().includes(match) ||
      o.snippet.toLowerCase().includes(match)
    ) {
      return false;
    }
  }
});
```

2021-11-26 10:04 UTC, artileda approved these changes

2021-11-26 17:19 UTC, lamualfa commented
![image](https://user-images.githubusercontent.com/39755201/143614447-72b4c12f-d233-48d0-b8a8-412502835902.png)

2021-11-26 17:44 UTC, aldy505 commented on src/services/search/filter.js
> +        o.snippet.toLowerCase().includes(match)) {return false;}
diomelin eslint

2021-11-26 18:03 UTC, merged