feat: new command for generate qr code using /qr <url>
teknologi-umum/bot pull request #170
Opened 2022-10-03 13:45 UTC by nblfikr

- [x] I've opened a Github issue beforehand
- [x] I've explained my PR in as much detail as possible.
- [ ] I'm using the conventional commit for my commit messages, or at least my commit messages are meaningful and easy to understand.
- [ ] I've added test files for new features.

2022-10-03 14:00 UTC, aldy505 requested changes

2022-10-03 14:00 UTC, aldy505 commented on src/services/qr/index.js
> +    return false;
inconsistent return, jangan gini

2022-10-03 14:00 UTC, aldy505 commented on src/services/qr/index.js
> +    return await QRCode.toDataURL(text);
```js
async function someFunction() {
  return await someOtherFunction();
}

// lalu

const result = await someFunction();
```

itu sama aja dengan

```js
const result = await someOtherFunction();
```

2022-10-04 01:25 UTC, aldy505 approved these changes

2022-10-04 01:45 UTC, elianiva approved these changes

2022-10-04 01:45 UTC, merged