feat: hackernews
teknologi-umum/bot pull request #206
Opened 2023-11-12 03:31 UTC by aldy505

![image](https://github.com/teknologi-umum/bot/assets/7274326/ee7731b8-0dd4-497d-8bd9-dc2a9ca218fd)
![image](https://github.com/teknologi-umum/bot/assets/7274326/1453daf5-e2c9-4071-8c58-dd401ae3112a)

2023-11-12 09:43 UTC, krowter commented on src/services/hackernews/index.js
> +    if (item?.time && item.time < last24Hours.getTime()) continue;
`item.time` kayaknya masih detik satuannya
https://hacker-news.firebaseio.com/v0/item/38224545.json

2023-11-12 09:46 UTC, krowter commented on src/services/hackernews/index.js
> +    if (item?.time && item.time < last24Hours.getTime()) continue;
Sisanya aman gan 👍

2023-11-13 01:39 UTC, elianiva requested changes

2023-11-13 01:39 UTC, elianiva commented on src/services/hackernews/index.js
> +  await context.telegram.sen1dMessage(
```suggestion
  await context.telegram.sendMessage(
```

2023-11-13 06:53 UTC, elianiva requested changes

2023-11-13 06:53 UTC, elianiva commented on src/services/hackernews/index.js
> +    if (item?.time && (item.time * 1000) < last24Hours.getTime()) continue;
kalo `item` null / undefined langsung continue aja, biar ngga kebanyakan optional chaining

2023-11-13 07:06 UTC, krowter approved these changes

2023-11-13 07:20 UTC, aldy505 commented on src/services/hackernews/index.js
> +    if (item?.time && (item.time * 1000) < last24Hours.getTime()) continue;
field nya yang mungkin null. `item` nggak mungkin null.

2023-11-15 00:05 UTC, elianiva commented on src/services/hackernews/index.js
> +    if (item?.time && (item.time * 1000) < last24Hours.getTime()) continue;
tapi `item?.type` implies item itu bisa null atau undefined

2023-11-15 00:06 UTC, aldy505 commented on src/services/hackernews/index.js
> +    if (item?.time && (item.time * 1000) < last24Hours.getTime()) continue;
baiklah

2023-11-15 04:19 UTC, elianiva approved these changes

2023-11-15 04:19 UTC, merged