feat: text preview
teknologi-umum/bot pull request #58
Opened 2021-08-29 23:09 UTC by elianiva

![image](https://user-images.githubusercontent.com/51877647/131268280-bcc13304-c065-4e2d-aa9a-a9a4ecbfb475.png)

2021-08-30 06:05 UTC, aldy505 requested changes

2021-08-30 06:05 UTC, aldy505 commented on src/services/search/search.js
> +    .get();
ini ngga di sanitize dulu? cek kalo clean apa nggak gitu.

kalo di sanitize, slice nya ntaran aja setelah itu.

2021-08-30 06:19 UTC, artileda approved these changes
Looks good, follow up comment dari om @aldy505 aja

2021-08-30 06:19 UTC, artileda commented on src/services/search/search.template.hbs
> +<a href="{{{best[idx].href}}}">{{{best[idx].text}}}</a>\n
Aku suka fitur ini ❤️❤️❤️

2021-08-30 08:18 UTC, elianiva commented on src/services/search/search.js
> +    .get();
woh iya, lupa ga sanitize yg ini

2021-08-30 14:19 UTC, aldy505 commented on src/services/search/search.js
> +    .get();
halah. dusta.

2021-08-30 14:20 UTC, elianiva commented
gatau ini kalo ada iklan gimana, ga bisa nyoba, ga dapet dapet

2021-08-30 16:42 UTC, artileda approved these changes

2021-08-30 16:44 UTC, aldy505 requested changes

2021-08-30 16:44 UTC, aldy505 commented on src/services/search/search.js
> +    .get();
so you won't forget. ini dijadiin satu aja biar ngapus iklannya sesuai.

![image](https://user-images.githubusercontent.com/7274326/131374435-0af380ea-5c7f-41d7-b817-2cfc1c509e3a.png)

2021-08-31 02:38 UTC, aldy505 approved these changes
mantap. merging.

2021-08-31 02:39 UTC, merged