Add Space
teknologi-umum/bot pull request #90
Opened 2021-09-17 06:28 UTC by farhan443

<a/>points => <a/> points﻿

2021-09-17 06:33 UTC, farhan443 commented
Bentar2, salah wkwk.

2021-09-17 09:51 UTC, farhan443 commented
Okee, udah

2021-09-17 09:52 UTC, aldy505 requested changes

2021-09-17 09:52 UTC, aldy505 commented on src/services/dukun/index.js
> +        }</a>${replyMessage.from.id.firstName}${replyMessage.from.id.lastName !== undefined ? ' ' + replyMessage.from.id.lastName : ''} points: ${updatedData.points}`,
this should be 

```js
`... ${replyMessage.from.firstName}${replyMessage.from.last_name !== undefined ? ' ' + replyMessage.from.last_name : ''} points: ...`

2021-09-17 09:52 UTC, aldy505 commented on src/services/dukun/index.js
> +      `Dukun <a href="tg://user?id=${replyMessage.from.id}">${replyMessage.from.firstName} ${
same with this one

2021-09-17 10:07 UTC, aldy505 approved these changes

2021-09-17 10:15 UTC, ronnygunawan requested changes
Changes requested. Sudah saya kasih note di tiap baris

2021-09-17 10:15 UTC, ronnygunawan commented on src/services/dukun/index.js
> +        replyMessage.from?.last_name !== undefined ? ' ' : ''
Ketambahan spasi dari line 153

2021-09-17 10:15 UTC, ronnygunawan commented on src/services/dukun/index.js
> +      }${replyMessage.from?.last_name ?? ''}</a> points: ${updatedData.points}`,
Bisa disederhanakan seperti line 113

2021-10-03 05:39 UTC, ronnygunawan approved these changes
LGTM

2021-10-03 05:41 UTC, merged